version: '2'

volumes:
    prometheus_data: {}
    grafana_data: {}

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    privileged: true
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
      - alertmanager:alertmanager
    depends_on:
      - cadvisor
    networks:
      - back-tier
  
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    privileged: true
    command:
      - '-web.listen-address=:9101'
    ports:
      - 9101:9101
    networks:
      - back-tier

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    privileged: true
    ports:
      - 9093:9093
    volumes: 
      - ./alertmanager:/etc/alertmanager
    networks:
      - back-tier
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    
  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    privileged: true
    restart: always
    volumes:
      - /:/rootfs:ro
      - /cgroup:/cgroup:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - back-tier
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    privileged: true
    restart: always
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - config.monitoring
    networks:
      - back-tier
      - front-tier
